# Generated by Django 4.0.4 on 2023-06-29 12:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musker', '0003_meep'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meep',
            new_name='Tweep',
        ),
    ]
